{%- if cookiecutter.db_type == "postgresql" %}
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL={{cookiecutter.db_type}}://user:password@db:5432/{{cookiecutter.project_slug}}
    depends_on:
      - db
    volumes:
      - .:/app

          db:
            image: postgres:15
            environment:
              POSTGRES_DB: {{cookiecutter.project_slug}}
              POSTGRES_USER: user
              POSTGRES_PASSWORD: password
            ports:
              - "5432:5432"
            volumes:
              - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
{%- endif %}
